apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ui
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - lassemg.dk
    - www.lassemg.dk
    secretName: portfolio-ui-tls
  rules:
  - host: lassemg.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-ui
            port:
              number: 80
  - host: www.lassemg.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-ui
            port:
              number: 80
